name: simple_deployment_pipeline

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with: 
          node-version: '16.x'
      - name: npm install
        run: npm install
      - run: npm ci
      - run: npx patch-package
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: npx browserslist@latest --update-db
        run: npx browserslist@latest --update-db
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          start: npm run start-prod
          command: npm run test:e2e
          wait-on: http://localhost:5000
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}} #Must be unique in Heroku
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          healthcheck: "https://${{secrets.HEROKU_APP_NAME}}.herokuapp.com/health"
          checkstring: "ok"
          delay: 5
          rollbackonhealthcheckfailed: true
